@ECHO OFF
@ECHO Executando todos os Arquivos SQL ...
@ECHO Executando "1_Tables.sql" ...
C:\wamp\bin\mysql\mysql5.5.8\bin\mysql -uroot dbjmmorpg <1_Tables.sql
@ECHO Executando "2_Inserts.sql" ...
C:\wamp\bin\mysql\mysql5.5.8\bin\mysql -uroot dbjmmorpg <2_Inserts.sql
@ECHO Finalizado ...
pause